#include "Pch.h"

#include "Debugger/SymbolDescriptions.h"





////////////////////////////////////////////////////////////////////////////////
//
//  What each shipped ROM symbol is, in a line: the names RomSymbols ships,
//  described from the machines' published behavior.
//
////////////////////////////////////////////////////////////////////////////////

static constexpr std::pair<const char *, const char *>  s_kDescriptions[] =
{
    { "WNDLFT", "Text window left edge (column)" },
    { "WNDWDTH", "Text window width" },
    { "WNDTOP", "Text window top line" },
    { "WNDBTM", "Text window bottom line + 1" },
    { "CH", "Cursor column" },
    { "CV", "Cursor row" },
    { "GBASL", "Lo-res graphics line base address, low byte" },
    { "GBASH", "Lo-res graphics line base address, high byte" },
    { "BASL", "Text line base address, low byte" },
    { "BASH", "Text line base address, high byte" },
    { "BAS2L", "Second text base address (scrolling), low byte" },
    { "BAS2H", "Second text base address (scrolling), high byte" },
    { "H2", "Lo-res line end column (HLINE)" },
    { "V2", "Lo-res line end row (VLINE)" },
    { "MASK", "Lo-res color mask for the current nibble" },
    { "COLOR", "Lo-res plotting color" },
    { "MODE", "Monitor command-line mode" },
    { "INVFLG", "Text output mask: $FF normal, $3F inverse, $7F flash" },
    { "PROMPT", "Prompt character GETLN prints" },
    { "YSAV", "Monitor scratch (saved Y)" },
    { "YSAV1", "Monitor scratch (saved Y)" },
    { "CSWL", "Character output hook, low byte (COUT jumps here)" },
    { "CSWH", "Character output hook, high byte" },
    { "KSWL", "Character input hook, low byte (RDKEY jumps here)" },
    { "KSWH", "Character input hook, high byte" },
    { "PCL", "Monitor program counter, low byte" },
    { "PCH", "Monitor program counter, high byte" },
    { "A1L", "Monitor address 1, low byte" },
    { "A1H", "Monitor address 1, high byte" },
    { "A2L", "Monitor address 2, low byte" },
    { "A2H", "Monitor address 2, high byte" },
    { "A3L", "Monitor address 3, low byte" },
    { "A3H", "Monitor address 3, high byte" },
    { "A4L", "Monitor address 4, low byte" },
    { "A4H", "Monitor address 4, high byte" },
    { "A5L", "Monitor address 5, low byte" },
    { "A5H", "Monitor address 5, high byte" },
    { "ACC", "Saved A register (Monitor)" },
    { "XREG", "Saved X register (Monitor)" },
    { "YREG", "Saved Y register (Monitor)" },
    { "STATUS", "Saved P register (Monitor)" },
    { "SPNT", "Saved stack pointer (Monitor)" },
    { "RNDL", "Random seed, low byte (counts while waiting for a key)" },
    { "RNDH", "Random seed, high byte" },
    { "IN", "Input buffer GETLN fills ($0200-$02FF)" },
    { "BRKV", "BRK handler vector" },
    { "SOFTEV", "Warm-start (Reset) vector" },
    { "PWREDUP", "Power-up byte: SOFTEV high EOR $A5 means warm start" },
    { "AMPERV", "Applesoft & command jump" },
    { "USRADR", "Applesoft USR() jump" },
    { "NMI", "NMI jump" },
    { "IRQLOC", "IRQ handler vector" },
    { "MSLOT", "Slot number ($Cn) of the active peripheral ROM" },
    { "PLOT", "Plot a lo-res point at (Y, A)" },
    { "HLINE", "Draw a lo-res horizontal line" },
    { "VLINE", "Draw a lo-res vertical line" },
    { "CLRSCR", "Clear the whole lo-res screen" },
    { "CLRTOP", "Clear the top 40 lines of lo-res" },
    { "GBASCALC", "Compute GBASL/GBASH for a lo-res row" },
    { "NXTCOL", "Next lo-res color" },
    { "SETCOL", "Set the lo-res plotting color" },
    { "SCRN", "Read the lo-res color at a point" },
    { "INSDS1", "Disassembler: print PC and instruction bytes" },
    { "INSDS2", "Disassembler: decode an opcode's length and mode" },
    { "INSTDSP", "Disassembler: display one instruction" },
    { "PRNTYX", "Print Y then X as hex" },
    { "PRNTAX", "Print A then X as hex" },
    { "PRNTX", "Print X as hex" },
    { "PRBLNK", "Print three spaces" },
    { "PRBL2", "Print X spaces" },
    { "PCADJ", "Advance PC past an instruction" },
    { "PREAD", "Read a paddle: X = paddle, Y = value" },
    { "INIT", "Set text mode, full window" },
    { "SETTXT", "Set text mode" },
    { "SETGR", "Set mixed lo-res graphics mode" },
    { "SETWND", "Set the full text window" },
    { "TABV", "Move the cursor to row A" },
    { "APPLEII", "Print the power-up title" },
    { "VTAB", "Compute the text base for the cursor row" },
    { "VTABZ", "Compute the text base for row A" },
    { "ESC1", "Handle an ESC cursor-movement key" },
    { "CLREOP", "Clear to the end of the page" },
    { "HOME", "Clear the text window and home the cursor" },
    { "CR", "Carriage return" },
    { "LF", "Line feed" },
    { "SCROLL", "Scroll the text window up a line" },
    { "CLREOL", "Clear to the end of the line" },
    { "CLEOLZ", "Clear the line from column Y" },
    { "WAIT", "Delay: about (26 + 27A + 5A^2)/2 cycles" },
    { "NXTA4", "Increment A4 and A1" },
    { "NXTA1", "Increment A1; carry when it passes A2" },
    { "HEADR", "Write a cassette header tone" },
    { "RDKEY", "Read a key through KSW, with the cursor" },
    { "KEYIN", "Read the keyboard, blinking the cursor" },
    { "RDCHAR", "Read a key, handling ESC sequences" },
    { "GETLNZ", "Get a line after a carriage return" },
    { "GETLN", "Get a line of input into IN, after the prompt" },
    { "GETLN1", "Get a line of input without the prompt" },
    { "CROUT1", "Clear to end of line, then carriage return" },
    { "CROUT", "Output a carriage return" },
    { "PRA1", "Print A1 as an address and a dash" },
    { "PRBYTE", "Print A as two hex digits" },
    { "PRHEX", "Print the low nibble of A as a hex digit" },
    { "COUT", "Output the character in A through CSW" },
    { "COUT1", "Output A to the screen" },
    { "COUTZ", "Output A to the screen (no INVFLG setup)" },
    { "IDROUTINE", "Identify the machine (IIe and later)" },
    { "MOVE", "Monitor M command: move memory" },
    { "VERIFY", "Monitor V command: compare memory" },
    { "LIST", "Monitor L command: disassemble" },
    { "SETINV", "Set inverse text" },
    { "SETNORM", "Set normal text" },
    { "SETKBD", "Set input to the keyboard" },
    { "INPORT", "Set input to slot A" },
    { "SETVID", "Set output to the screen" },
    { "OUTPORT", "Set output to slot A" },
    { "GO", "Monitor G command: run at A1" },
    { "WRITE", "Write memory to cassette" },
    { "READ", "Read memory from cassette" },
    { "BELL", "Beep" },
    { "RESTORE", "Restore A, X, Y and P from the save area" },
    { "SAVE", "Save A, X, Y, P and S to the save area" },
    { "OLDRST", "Monitor reset entry" },
    { "MON", "Enter the Monitor with a beep" },
    { "MONZ", "Enter the Monitor" },
    { "BELL1", "Beep (1 kHz for 0.1 s)" },
    { "BELL2", "Beep, without the delay first" },
    { "STORADV", "Store A on screen and advance the cursor" },
    { "ADVANCE", "Advance the cursor" },
    { "VIDOUT", "Output A to the screen, handling control characters" },
    { "BS", "Backspace" },
    { "UP", "Move the cursor up" },
    { "RESET", "Reset handler: the 6502 starts here, through the vector at $FFFC" },
    { "PWRUP", "Power-up (cold start) sequence" },
    { "SLOOP", "Boot scan: look for a disk controller ROM" },
    { "REGDSP", "Display the saved registers" },
    { "RGDSP1", "Display the saved registers (no CR)" },
    { "IRQ", "IRQ/BRK handler" },
    { "BREAK", "BRK handler: save registers, show them" },
    { "OLDBRK", "Old BRK entry: display registers, enter the Monitor" },
    { "NMIVECT", "NMI vector" },
    { "RESETVECT", "Reset vector: where the 6502 starts at power-on and Reset" },
    { "IRQVECT", "IRQ/BRK vector" },
    { "KBD", "Read: keyboard data; bit 7 set when a key is waiting" },
    { "KBDSTRB", "Read or write: clear the keyboard strobe (bit 7 of KBD)" },
    { "TAPEOUT", "Toggle the cassette output" },
    { "SPKR", "Toggle the speaker (each access is a click)" },
    { "STROBE", "Game I/O strobe output" },
    { "TXTCLR", "Graphics mode on" },
    { "TXTSET", "Text mode on" },
    { "MIXCLR", "Full-screen graphics" },
    { "MIXSET", "Mixed graphics with four lines of text" },
    { "TXTPAGE1", "Display page 1 (with 80STORE on: main memory for $0400/$2000)" },
    { "TXTPAGE2", "Display page 2 (with 80STORE on: aux memory for $0400/$2000)" },
    { "LORES", "Lo-res graphics" },
    { "HIRES", "Hi-res graphics" },
    { "SETAN0", "Annunciator 0 on" },
    { "CLRAN0", "Annunciator 0 off" },
    { "SETAN1", "Annunciator 1 on" },
    { "CLRAN1", "Annunciator 1 off" },
    { "SETAN2", "Annunciator 2 on" },
    { "CLRAN2", "Annunciator 2 off" },
    { "SETAN3", "Annunciator 3 on (IIe: double hi-res off)" },
    { "CLRAN3", "Annunciator 3 off (IIe: double hi-res on)" },
    { "TAPEIN", "Read: cassette input in bit 7" },
    { "BUTN0", "Read: button 0 (Open Apple) in bit 7" },
    { "BUTN1", "Read: button 1 (Closed Apple) in bit 7" },
    { "BUTN2", "Read: button 2 in bit 7" },
    { "PADDL0", "Read: paddle 0 timer in bit 7" },
    { "PADDL1", "Read: paddle 1 timer in bit 7" },
    { "PADDL2", "Read: paddle 2 timer in bit 7" },
    { "PADDL3", "Read: paddle 3 timer in bit 7" },
    { "PTRIG", "Start the paddle timers" },
    { "80STOREOFF", "Write: PAGE2 selects the display page" },
    { "80STOREON", "Write: PAGE2 selects main or aux display memory" },
    { "RAMRDOFF", "Write: read $0200-$BFFF from main memory" },
    { "RAMRDON", "Write: read $0200-$BFFF from aux memory" },
    { "RAMWRTOFF", "Write: write $0200-$BFFF to main memory" },
    { "RAMWRTON", "Write: write $0200-$BFFF to aux memory" },
    { "INTCXROMOFF", "Write: slot ROMs at $C100-$CFFF" },
    { "INTCXROMON", "Write: internal ROM at $C100-$CFFF" },
    { "ALTZPOFF", "Write: main zero page, stack and language card" },
    { "ALTZPON", "Write: aux zero page, stack and language card" },
    { "SLOTC3ROMOFF", "Write: internal ROM at $C300" },
    { "SLOTC3ROMON", "Write: slot 3 ROM at $C300" },
    { "80COLOFF", "Write: 40-column display" },
    { "80COLON", "Write: 80-column display" },
    { "ALTCHARSETOFF", "Write: primary character set (flashing)" },
    { "ALTCHARSETON", "Write: alternate character set (MouseText)" },
    { "RDLCBNK2", "Read: bit 7 set when language card bank 2 is selected" },
    { "RDLCRAM", "Read: bit 7 set when language card RAM is read" },
    { "RDRAMRD", "Read: bit 7 set when reading aux memory" },
    { "RDRAMWRT", "Read: bit 7 set when writing aux memory" },
    { "RDCXROM", "Read: bit 7 set when internal $Cx ROM is in" },
    { "RDALTZP", "Read: bit 7 set when aux zero page is in" },
    { "RDC3ROM", "Read: bit 7 set when slot 3 ROM is in" },
    { "RD80STORE", "Read: bit 7 set when 80STORE is on" },
    { "RDVBL", "Read: bit 7 reflects vertical blanking" },
    { "RDTEXT", "Read: bit 7 set in text mode" },
    { "RDMIXED", "Read: bit 7 set in mixed mode" },
    { "RDPAGE2", "Read: bit 7 set when page 2 is selected" },
    { "RDHIRES", "Read: bit 7 set in hi-res mode" },
    { "RDALTCHAR", "Read: bit 7 set with the alternate character set" },
    { "RD80COL", "Read: bit 7 set in 80-column mode" },
    { "DHIRESON", "Double hi-res on (with 80COL and HIRES)" },
    { "DHIRESOFF", "Double hi-res off" },
    { "LCBANK2", "Language card: read RAM bank 2 (read twice to write-enable)" },
    { "LCBANK1", "Language card: read RAM bank 1 (read twice to write-enable)" },
    { "ROMIN", "Language card: read ROM (read twice to write-enable RAM)" },
    { "LINNUM", "Applesoft line number / 16-bit argument" },
    { "TXTTAB", "Applesoft program start" },
    { "VARTAB", "Applesoft simple variables start" },
    { "ARYTAB", "Applesoft arrays start" },
    { "STREND", "Applesoft end of arrays (free memory starts)" },
    { "FRETOP", "Applesoft bottom of string space" },
    { "MEMSIZ", "Applesoft HIMEM" },
    { "CURLIN", "Applesoft current line number" },
    { "OLDLIN", "Applesoft line where the program stopped" },
    { "OLDTEXT", "Applesoft text pointer where it stopped" },
    { "DATLIN", "Applesoft line of the current DATA" },
    { "DATPTR", "Applesoft pointer to the next DATA item" },
    { "VARNAM", "Applesoft variable name being looked up" },
    { "VARPNT", "Applesoft pointer to the variable's value" },
    { "FORPNT", "Applesoft FOR variable pointer" },
    { "FAC", "Applesoft floating-point accumulator" },
    { "FACSIGN", "Sign of FAC" },
    { "ARG", "Applesoft floating-point argument" },
    { "ARGSIGN", "Sign of ARG" },
    { "CHRGET", "Applesoft: advance TXTPTR and get the next character" },
    { "CHRGOT", "Applesoft: get the current character again" },
    { "TXTPTR", "Applesoft program text pointer" },
    { "RNDSEED", "Applesoft RND seed" },
    { "HGRX", "Hi-res cursor X" },
    { "HGRY", "Hi-res cursor Y" },
    { "HGRCOLOR", "Hi-res color byte" },
    { "HPAG", "Hi-res page being drawn ($20 or $40)" },
    { "SCALE", "Shape scale" },
    { "SHAPETBL", "Shape table address" },
    { "ROT", "Shape rotation" },
    { "COLDSTART", "Applesoft cold start" },
    { "RESTART", "Applesoft warm start" },
    { "ERROR", "Applesoft: report the error in X" },
    { "NEWSTT", "Applesoft: execute the next statement" },
    { "FRMNUM", "Applesoft: evaluate a numeric expression into FAC" },
    { "FRMEVL", "Applesoft: evaluate any expression" },
    { "CHKCOM", "Applesoft: require a comma" },
    { "SYNCHR", "Applesoft: require the character in A" },
    { "PTRGET", "Applesoft: find or create a variable" },
    { "GETBYT", "Applesoft: evaluate a byte into X" },
    { "GTBYTC", "Applesoft: advance, then GETBYT" },
    { "COMBYTE", "Applesoft: comma, then GETBYT" },
    { "GETADR", "Applesoft: FAC to a 16-bit address in LINNUM" },
    { "GIVAYF", "Applesoft: signed integer in A,Y to FAC" },
    { "GETNUM", "Applesoft: address, comma, byte" },
    { "SNGFLT", "Applesoft: Y to FAC" },
    { "FADD", "Applesoft: FAC = memory + FAC" },
    { "FSUB", "Applesoft: FAC = memory - FAC" },
    { "FMULT", "Applesoft: FAC = memory * FAC" },
    { "FDIV", "Applesoft: FAC = memory / FAC" },
    { "MOVFM", "Applesoft: load FAC from memory" },
    { "MOVMF", "Applesoft: store FAC to memory" },
    { "FLOAT", "Applesoft: A to FAC" },
    { "QINT", "Applesoft: FAC to a 32-bit integer" },
    { "STROUT", "Applesoft: print the string at A,Y" },
    { "LINPRT", "Applesoft: print X,A as a decimal number" },
    { "FOUT", "Applesoft: FAC to a string" },
    { "HPOSN", "Hi-res: position the cursor" },
    { "HPLOT", "Hi-res: plot a point" },
    { "HLIN", "Hi-res: draw a line to (A,X), Y" },
    { "HFIND", "Hi-res: find the cursor's coordinates" },
    { "DRAW", "Hi-res: draw a shape" },
    { "XDRAW", "Hi-res: draw a shape with XOR" },
    { "HGR2", "Hi-res page 2, full screen" },
    { "HGR", "Hi-res page 1, mixed" },
    { "HCLR", "Clear the hi-res page to black" },
    { "BKGND", "Clear the hi-res page to the color in A" },
    { "HCOLOR", "Set the hi-res color" },
    { "AMPERSAND", "Applesoft & command jump" },
    { "DOSWARM", "DOS 3.3 warm start" },
    { "DOSCOLD", "DOS 3.3 cold start" },
    { "RWTS", "DOS 3.3: call RWTS with an IOB" },
    { "FMPARM", "DOS 3.3: file manager parameter list" },
    { "RWTSPARM", "DOS 3.3: RWTS IOB address" },
    { "CONNECT", "DOS 3.3: reconnect the I/O hooks" },
    { "DOS", "DOS 3.3 image start" },
    { "MLI", "ProDOS MLI entry: JSR, then call number and parameter address" },
    { "JSPARE", "ProDOS: jump to the system program" },
    { "DATETIME", "ProDOS: read the clock" },
    { "SYSERR", "ProDOS: report a system error" },
    { "SYSDEATH", "ProDOS: fatal system error" },
    { "SERR", "ProDOS: last error code" },
    { "DEVADR", "ProDOS: device driver addresses" },
    { "DEVNUM", "ProDOS: last device used" },
    { "DEVCNT", "ProDOS: device count - 1" },
    { "DEVLST", "ProDOS: device list" },
    { "BITMAP", "ProDOS: memory bitmap" },
    { "BUFTBL", "ProDOS: open file buffer table" },
    { "DATELO", "ProDOS: date, low byte" },
    { "DATEHI", "ProDOS: date, high byte" },
    { "TIMELO", "ProDOS: time, minute" },
    { "TIMEHI", "ProDOS: time, hour" },
    { "LEVEL", "ProDOS: file level" },
    { "BUBIT", "ProDOS: backup bit" },
    { "SPARE1", "ProDOS: reserved" },
    { "MACHID", "ProDOS: machine identification byte" },
    { "SLTBYT", "ProDOS: slot ROM map" },
    { "PFIXPTR", "ProDOS: prefix active flag" },
    { "MLIACTV", "ProDOS: MLI active flag" },
    { "CMDADR", "ProDOS: return address of the last MLI call" },
    { "SAVEX", "ProDOS: saved X" },
    { "SAVEY", "ProDOS: saved Y" },
    { "IBAKVER", "ProDOS: minimum interpreter version" },
    { "IVERSION", "ProDOS: interpreter version" },
    { "KVERSION", "ProDOS: kernel version" },
};





////////////////////////////////////////////////////////////////////////////////
//
//  SymbolDescriptions::ChooseByDirection
//
//  A description opening "Write:" belongs to a write and one opening "Read:"
//  to a read; "Read or write:" and an undescribed name suit either. Where
//  nothing matches, the first name stands, which is what the caller would
//  have shown anyway.
//
////////////////////////////////////////////////////////////////////////////////

std::string SymbolDescriptions::ChooseByDirection (const std::vector<std::string> & names, bool isWrite)
{
    const char *  wanted = isWrite ? "Write:" : "Read:";



    for (const std::string & name : names)
    {
        const char *  description = Find (name);

        if (description != nullptr && std::string_view (description).starts_with (wanted))
        {
            return name;
        }
    }

    return names.empty() ? std::string() : names.front();
}





////////////////////////////////////////////////////////////////////////////////
//
//  SymbolDescriptions::Find
//
////////////////////////////////////////////////////////////////////////////////

const char * SymbolDescriptions::Find (const std::string & name)
{
    for (const auto & [symbol, description] : s_kDescriptions)
    {
        if (name == symbol)
        {
            return description;
        }
    }

    return nullptr;
}
