"""Bakes the Disk II faceplate legends into silhouette masks.

The legends were a hand-authored 7x9 pixel grid, which is pixel ART: at the
size they sit on the faceplate one cell lands on about a screen pixel, so the
staircase IS the letterform and anti-aliasing has nothing to soften. Baking
from a real grotesque at 64px puts the mask's own cells well under a pixel,
and what the eye resolves is the typeface.

Writes Casso/Ui/Scene/DeskSceneFaceLabels.h. Run it from anywhere:

    python scripts/modelgen/bake_face_labels.py
"""

import io
import os
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname (os.path.dirname (os.path.dirname (os.path.abspath (__file__))))
OUT  = os.path.join (ROOT, "Casso", "Ui", "Scene", "DeskSceneFaceLabels.h")

FONT  = r"C:\Windows\Fonts\arialbd.ttf"
PX    = 64          # rasterize tall, so the mask's own cells fall sub-pixel
TRACK = 0.16        # extra advance as a fraction of the em -- the real
                    # faceplate legends are letterspaced

font = ImageFont.truetype (FONT, PX)
buf  = io.StringIO()


def render (text):
    """Draws `text` letterspaced, on a canvas with room to spare."""
    pad = PX
    im  = Image.new ("L", (pad * 2 + int (PX * 1.4 * len (text)), PX * 3), 0)
    d   = ImageDraw.Draw (im)
    x   = float (pad)

    for ch in text:
        d.text ((x, pad), ch, fill = 255, font = font)
        x += d.textlength (ch, font = font) + PX * TRACK

    return im


def emit (text, name, pointer = False):
    """Rasterizes one legend and appends it to the header buffer."""
    im = render (text)

    if pointer:
        # The LED pointer: a solid right-pointing triangle, set on the text's
        # own optical center so it reads as part of the legend line.
        box = im.getbbox()
        h   = box[3] - box[1]
        th  = int (h * 0.62)
        x0  = box[2] + int (PX * 0.52)
        cy  = (box[1] + box[3]) // 2

        ImageDraw.Draw (im).polygon ([(x0, cy - th // 2),
                                      (x0, cy + th // 2),
                                      (x0 + int (th * 0.86), cy)], fill = 255)

    im   = im.crop (im.getbbox())
    rows = ["".join ("#" if im.getpixel ((x, y)) > 110 else "."
                     for x in range (im.width))
            for y in range (im.height)]

    buf.write ("// \"%s\"%s.\n" % (text, " and the pointer" if pointer else ""))
    buf.write ("static const char * const  %s[] =\n{\n" % name)

    for r in rows:
        buf.write ("    \"%s\",\n" % r)

    buf.write ("};\n\n")
    buf.write ("static constexpr int  k%sRows = %d;\n" % (name[3:], len (rows)))
    buf.write ("static constexpr int  k%sCols = %d;\n\n\n" % (name[3:], len (rows[0])))

    return len (rows)


rows = emit ("DRIVE 1", "s_kDrive1Mask")
emit ("DRIVE 2", "s_kDrive2Mask")
emit ("IN USE",  "s_kInUseMask", pointer = True)

HEADER = '''#pragma once





////////////////////////////////////////////////////////////////////////////////
//
//  DeskSceneFaceLabels.h
//
//  The Disk II faceplate legends as silhouette masks, baked from Arial Bold
//  at %dpx with %.0f%%%% letterspacing.
//
//  They were a hand-authored 7x9 grid, which is pixel ART. At the size the
//  legends sit on the faceplate one of those cells lands on about a screen
//  pixel, so the staircase IS the letterform and anti-aliasing has nothing to
//  soften -- the labels read as a chunky approximation of type rather than as
//  type. At %d rows the cells fall well under a pixel even zoomed in, and what
//  the eye resolves is the typeface.
//
//  Rows run top-down and every row is the same length, which is what lets
//  StampFaceMask merge each one into horizontal runs. '#' is ink.
//
//  GENERATED by scripts/modelgen/bake_face_labels.py. Edit that, not this.
//
////////////////////////////////////////////////////////////////////////////////


''' % (PX, TRACK * 100.0, rows)

with open (OUT, "w", newline = "\r\n") as f:
    f.write (HEADER + buf.getvalue())

print ("wrote %s" % OUT)
