"""Build CassoEmuCore/CassoExplorer/CassoExplorerIcons.h from the Fluent SVGs.

The icons are Microsoft's Fluent UI System Icons (MIT; the license is in
Resources/Icons/Fluent/LICENSE), at 20 pixels: outlines, and the filled
dots where Explorer's overflow is that weight. Each is one path
of several sub-shapes, and the table below says which sub-shapes File
Explorer draws in the accent -- the plus inside New's ring, the arrow Sort
points down with -- and which in the foreground ink. The indices were read
off each icon drawn with its sub-shapes numbered; Explorer's own command bar,
captured with a file selected, gave the tones.

Run after changing an icon or its tones:

    python scripts/GenFluentIcons.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'Resources' / 'Icons' / 'Fluent'
OUTPUT = ROOT / 'CassoEmuCore' / 'CassoExplorer' / 'CassoExplorerIcons.h'

#  name -> (file stem after ic_fluent_, [(sub-shape indices, accent, band
#  top, band bottom)]). Stems end in the size and the style.
#  A band of (0, 0) is the whole icon.
ICONS = {
    'New':     ('add_circle_20_regular',        [([0], True, 0, 0), ([1, 2], False, 0, 0)]),
    #  The scissors' handle loops and blades are one outline, so the tones
    #  split where the loops begin rather than by sub-shape.
    'Cut':     ('cut_20_regular',               [([0, 1, 2, 3], False, 0, 11.2), ([0, 1, 2], True, 11.2, 20)]),
    'Copy':    ('copy_20_regular',              [([0], False, 0, 0), ([1, 2], True, 0, 0)]),
    'Paste':   ('clipboard_paste_20_regular',   [([0, 1], False, 0, 0), ([2, 3], True, 0, 0)]),
    #  Explorer's Rename is the A in brackets with a text cursor: the A and
    #  the cursor in the accent, the brackets in the ink.
    'Rename':  ('rename_a_20_regular',          [([0, 3, 4], True, 0, 0), ([1, 2], False, 0, 0)]),
    'Delete':  ('delete_20_regular',            [([0, 1, 2, 3, 4], False, 0, 0)]),
    'Sort':    ('arrow_sort_20_regular',        [([0], False, 0, 0), ([1], True, 0, 0)]),
    'View':    ('line_horizontal_4_20_regular', [([0, 1, 2, 3], False, 0, 0)]),
    #  The filled dots, which are Explorer's weight; the outline ones are thin.
    'More':    ('more_horizontal_20_filled',    [([0, 1, 2], False, 0, 0)]),
    'Preview': ('panel_right_20_regular',       [([0, 1, 2], False, 0, 0)]),
    'Theme':   ('dark_theme_20_regular',        [([0, 1], False, 0, 0)]),
}

B = '/' * 80


def path_of(name):
    svg = (SOURCE / f'ic_fluent_{name}.svg').read_text(encoding='utf-8')
    paths = re.findall(r'<path[^>]*\sd="([^"]+)"', svg)
    assert len(paths) == 1, f'{name}: expected one path, found {len(paths)}'
    return paths[0]


def mask(indices):
    value = 0

    for i in indices:
        value |= 1 << i

    return value


def main():
    lines = []
    out = lines.append

    out('#pragma once')
    out('')
    out('#include "Render/DxuiVectorIcon.h"')
    out('')
    out('')
    out('')
    out('')
    out('')
    out(B)
    out('//')
    out('//  CassoExplorerIcons')
    out('//')
    out('//  GENERATED by scripts/GenFluentIcons.py from Resources/Icons/Fluent.')
    out('//  Edit the script, not this file.')
    out('//')
    out("//  The command bar's icons: Microsoft's Fluent UI System Icons, MIT")
    out('//  licensed, in the two tones File Explorer gives them.')
    out('//')
    out(B)
    out('')
    out('namespace CassoExplorerIcons')
    out('{')

    for name, (svg, layers) in ICONS.items():
        d = path_of(svg)

        #  One string literal per line, so the header stays readable.
        chunks = re.findall(r'.{1,100}(?:\s|$)|.{1,100}', d)
        chunks = [c for c in chunks if c]

        out('')
        out(f'    //  {svg}')
        out(f'    static constexpr DxuiVectorIconLayer  s_k{name}Layers[] =')
        out('    {')

        for indices, accent, top, bottom in layers:
            out(f'        {{ 0x{mask(indices):02X}u, {"true " if accent else "false"}, {top:.1f}f, {bottom:.1f}f }},')

        out('    };')
        out('')
        out(f'    static constexpr DxuiVectorIcon  s_k{name} =')
        out('    {')

        for i, chunk in enumerate(chunks):
            lead = '        L"'
            out(f'{lead}{chunk}"' + (',' if i == len(chunks) - 1 else ''))

        out(f'        20.0f, s_k{name}Layers, std::size (s_k{name}Layers)')
        out('    };')

    out('}')
    out('')

    OUTPUT.write_text('\r\n'.join(lines), encoding='utf-8', newline='')
    print(f'wrote {OUTPUT.relative_to(ROOT)} ({len(ICONS)} icons)')


if __name__ == '__main__':
    main()
