#include "Pch.h"
#include "DemoAssets.h"

#include "Cpu.h"
#include "Assembler.h"
#include "AssemblerTypes.h"

#include "GuestSession.h"
#include "HeadlessHost.h"
#include "KeystrokeInjector.h"
#include "Devices/Disk/DiskImageStore.h"
#include "Devices/Disk/NibblizationLayer.h"
#include "Devices/Disk2Controller.h"
#include "Devices/Apple2eSoftSwitchBank.h"
#include "Video/AppleHiResMode.h"
#include "TextScreenScraper.h"

using namespace Microsoft::VisualStudio::CppUnitTestFramework;
namespace fs = std::filesystem;





////////////////////////////////////////////////////////////////////////////////
//
//  BootDiskTests
//
//  End-to-end gate for the full Apple //e disk-boot pipeline using a
//  100% in-house demo disk -- no third-party software, no copyrighted
//  content. Source for the demo lives at
//  Apple2/Demos/CassoRocks/casso-rocks.a65; the framebuffer payload at
//  Apple2/Demos/CassoRocks/cassowary.hgr is generated by HgrPreprocess.py
//  in that same folder, from one of the cassowary photos under
//  Assets/. This test assembles the .a65 via Casso's own AS65-compatible
//  assembler, stitches the HGR payload behind the boot sector at file
//  offset $1000 (track 1 sector 0), mounts the resulting .dsk through
//  DiskImageStore, lets the //e boot ROM pick it up, and verifies the
//  demo:
//
//    - reads the 8 KB framebuffer off tracks 1+2 (32 sectors) into
//      $2000-$3FFF using a from-scratch 6502 RWTS,
//    - flips the soft switches into HGR1 mode (TEXT off, MIXED off,
//      PAGE2 off, HIRES on),
//    - leaves the cassowary on screen.
//
//  Exercises: HgrPreprocess.py output -> Assembler -> NibblizationLayer
//  -> DiskImageStore -> Disk2Controller -> Disk2NibbleEngine ->
//  Disk2.rom slot 6 boot -> 6502 CPU executing our RWTS -> MMU HGR
//  page-1 writes -> Apple2eSoftSwitchBank graphics-mode latching.
//
//  THE CHEAP QUESTIONS COME FIRST. The demo has no operating system to fall
//  back on -- the boot ROM reads track 0's first sector and jumps into it, and
//  a stitched image the drive cannot read makes the 6502 execute the framebuffer
//  instead. This build writes an instruction look-back for every illegal opcode
//  it reaches, so that failure is measured in gigabytes rather than in a red
//  assertion. Both questions below are asked of the mounted container and
//  before the processor is pointed at the boot ROM.
//
////////////////////////////////////////////////////////////////////////////////



TEST_CLASS (BootDiskTests)
{
public:

    static constexpr int       kMaxAncestorWalk  = 10;
    static constexpr size_t    kHgrPayloadSize   = 8192;
    static constexpr size_t    kSectorByteSize   = 256;
    static constexpr int       kSectorsPerTrack  = 16;
    static constexpr int       kStage2Sectors    = 3;      // stage 2 spans three sectors
    static constexpr Word      kHgrBase          = 0x2000;
    static constexpr Word      kDemoEntry        = 0x0801;
    static constexpr Word      kStage2Entry      = 0x1000;
    static constexpr int       kSignOffRow       = 21;
    static constexpr int       kPromptRow        = 23;

    //  The line the demo leaves on the screen on its way out.
    static constexpr const char *  kSignOffText =
        "THANKS FOR WATCHING THE CASSO DEMO.";

    //  A track read is 18 sector slots -- see read_track's comment on why it
    //  over-reads -- which is 1.125 revolutions, about 750k cycles once head
    //  stepping and resync are counted. Thirteen tracks is therefore ~9.8M,
    //  and the 10M this used to be was not the 5x headroom its comment
    //  claimed: at nine tracks it was already only ~1.4x, and the thirteenth
    //  track ran off the end of it. The symptom was subtle enough to be worth
    //  naming -- the demo's RWTS stores the 6-bit values first and merges the
    //  2-bit auxiliaries in a second pass, so a read cut short mid-sector
    //  leaves bytes that look like the right data shifted right by two.
    static constexpr uint64_t  kDemoCycleBudget  = 20'000'000ULL;   // 20M cycles ≈ 19.6 sec emulated, ~2x what 13 tracks need


    // Walks up from the test's working directory (x64\Debug) looking for a
    // repo-relative path. Capped at kMaxAncestorWalk so a checkout mounted
    // near a drive root cannot climb past it. Empty means "not in this
    // checkout" -- callers skip rather than fail, since the demo sources are
    // not present in every clone.
    fs::path FindRepoFile (const std::string & relPath)
    {
        std::error_code ec;
        fs::path        cursor  = fs::current_path (ec);
        fs::path        found;
        bool            walking = !ec;

        for (int i = 0; walking && found.empty() && i < kMaxAncestorWalk; i++)
        {
            fs::path candidate = cursor / relPath;

            if (fs::exists (candidate, ec))
            {
                found = candidate;
            }
            else if (!cursor.has_parent_path() || cursor == cursor.parent_path())
            {
                // Reached the drive root with nothing found.
                walking = false;
            }
            else
            {
                cursor = cursor.parent_path();
            }
        }

        return found;
    }


    // Unreadable reads as empty; the caller has already decided the file
    // exists, so an empty result surfaces as an assertion on the content.
    std::string ReadFileText (const fs::path & path)
    {
        std::string    text;



        std::ifstream  f (path);

        if (f)
        {
            text.assign ((std::istreambuf_iterator<char> (f)),
                         std::istreambuf_iterator<char> ());
        }

        return text;
    }


    //  The screen do_exit hands over, and proof that what it handed to is
    //  really Applesoft.
    //
    //  do_exit writes its sign-off on row 21 and leaves the cursor on that
    //  same row, from where Applesoft's own two carriage returns -- one in
    //  the cold start, one at the head of the READY loop -- put the "]" on
    //  row 23 without scrolling anything.
    //
    //  TYPING IS THE PART NO SOFT-SWITCH ASSERTION CAN STAND IN FOR. It
    //  exercises CSW, KSW, the text window and the 40-column screen at
    //  once, and every exit bug this demo has had presented as a machine
    //  that looked settled and could not be typed at: 80COL left on so
    //  COUT wrote 40-column output onto an 80-column screen, and an ESC
    //  left in the keyboard latch for GETLN to read as a cursor move and
    //  swallow the next character with.
    void AssertSignedOffToBasic (EmulatorCore & core,
                                 const wchar_t * route,
                                 size_t          togglesBeforeExit)
    {
        std::vector<std::string>  screen;
        wchar_t                   msg[256]  = {};
        const char *              typed     = "PRINT 2+2";
        const char *              echo      = "]PRINT 2+2";
        size_t                    echoRow   = 0;
        bool                      echoed    = false;

        screen = TextScreenScraper::Scrape40 (*core.bus, 0x0400);

        Assert::IsTrue (screen.size() > size_t (kPromptRow),
            L"the text screen must have all 24 rows");

        Assert::IsTrue (
            screen[kSignOffRow].find (kSignOffText) != std::string::npos,
            (swprintf_s (msg, L"%ls: the sign-off must be on row %d, which "
                              L"reads \"%hs\".",
                         route, kSignOffRow, screen[kSignOffRow].c_str()), msg));

        Assert::AreEqual (']', screen[kPromptRow][0],
            L"Applesoft's prompt must be in column 0 of the bottom row");

        Assert::IsFalse (core.diskController->IsMotorOn(),
            L"the drive must be stopped by the time the demo hands over");

        //  AND IT LEAVES QUIETLY. The //e's reset handler bells on its way
        //  past -- JSR $FF3A at $FA62+$20, 192 speaker toggles, and it runs
        //  on the power-on boot as well as on Ctrl-Reset -- so an exit
        //  routed through ($FFFC) beeped every single time. That beep was
        //  indistinguishable from the one a reset makes, which cost real
        //  time diagnosing an exit: a machine that eventually reached the
        //  prompt and beeped on the way looked like a delayed reset rather
        //  than a delayed keystroke. Going to $E000 direct is silent, and
        //  this is what holds it there.
        Assert::AreEqual (togglesBeforeExit,
            core.speaker->GetToggleTimestamps().size(),
            (swprintf_s (msg, L"%ls: the exit must not touch the speaker.",
                         route), msg));

        for (size_t i = 0; typed[i] != '\0'; i++)
        {
            core.keyboard->PressKey (typed[i]);
            core.RunCycles (100'000ULL);
        }

        core.keyboard->PressKey ('\r');
        core.RunCycles (2'000'000ULL);

        screen = TextScreenScraper::Scrape40 (*core.bus, 0x0400);

        for (size_t r = 0; !echoed && r + 1 < screen.size(); r++)
        {
            if (screen[r].find (echo) != std::string::npos)
            {
                echoRow = r;
                echoed  = true;
            }
        }

        Assert::IsTrue (echoed,
            (swprintf_s (msg, L"%ls: Applesoft must echo what is typed at it.",
                         route), msg));

        Assert::AreEqual ('4', screen[echoRow + 1][0],
            (swprintf_s (msg, L"%ls: Applesoft must run what is typed at it "
                              L"-- PRINT 2+2 must print 4.", route), msg));
    }


    std::vector<Byte> ReadFileBytes (const fs::path & path)
    {
        std::vector<Byte>  bytes;



        std::ifstream      f (path, std::ios::binary);

        if (f)
        {
            bytes.assign ((std::istreambuf_iterator<char> (f)),
                          std::istreambuf_iterator<char> ());
        }

        return bytes;
    }

    //
    //  NOTHING IN HERE OPENS A FILE.
    //
    //  The demo's two sources and its seven payloads are compiled into the test
    //  assembly by DemoAssets.rc, so the resource compiler reads them at build
    //  time and this test reads a pointer into its own module image.
    //
    //  It used to read all nine off the repo and write the built image back
    //  over Apple2/Demos/casso-rocks.dsk. The write normally put the same
    //  bytes there, so the only trace was a changed timestamp, until a run
    //  that built a different image and left a corrupted asset in the tree.
    //  Reading was the same mistake in miniature: a test that reads the tree
    //  reports on the machine it happens to be running on, and skipped itself
    //  entirely on a checkout arranged differently -- which is a test that can
    //  pass by not running.
    //
    //  THE SKIP IS GONE WITH THE READS. An embedded resource is either in the
    //  assembly or the assembly did not build, so there is no absence left to
    //  tolerate and no way for this to quietly not run.
    //
    TEST_METHOD (CassoRocks_DemoDisk_DisplaysHgrCassowary)
    {
        {
            std::string              source          = DemoAssets::GetText (IDR_DEMO_STAGE1_SRC);
            std::string              stage2Source    = DemoAssets::GetText (IDR_DEMO_STAGE2_SRC);
            std::vector<Byte>        hgrPayload;
            std::vector<Byte>        hgrMonoPayload;
            std::vector<Byte>        dhgrAuxPayload;
            std::vector<Byte>        dhgrMainPayload;
            std::vector<Byte>        monoAuxPayload;
            std::vector<Byte>        monoMainPayload;
            Cpu                      cpu;
            HeadlessHost             host;
            EmulatorCore             core;
            HRESULT                  hr              = S_OK;
            DiskImage              * img             = nullptr;
            Apple2eSoftSwitchBank  * ss              = nullptr;
            Byte                   * auxBuf          = nullptr;
            size_t                   quietMark       = 0;
            AssemblyResult           asmResult;
            AssemblyResult           stage2Result;
            Assert::IsFalse (source.empty(), L"casso-rocks.a65 must not be empty");
            Assert::IsFalse (stage2Source.empty(),
                L"casso-rocks-stage2.a65 must not be empty");

            hgrPayload      = DemoAssets::Copy (IDR_DEMO_HGR);
            hgrMonoPayload  = DemoAssets::Copy (IDR_DEMO_HGR_MONO);
            dhgrAuxPayload  = DemoAssets::Copy (IDR_DEMO_DHGR_AUX);
            dhgrMainPayload = DemoAssets::Copy (IDR_DEMO_DHGR_MAIN);
            monoAuxPayload  = DemoAssets::Copy (IDR_DEMO_DHGR_MONO_AUX);
            monoMainPayload = DemoAssets::Copy (IDR_DEMO_DHGR_MONO_MAIN);
            Assert::AreEqual (kHgrPayloadSize, hgrPayload.size(),
                L"cassowary.hgr must be exactly 8192 bytes");
            Assert::AreEqual (kHgrPayloadSize, hgrMonoPayload.size(),
                L"cassowary-mono.hgr must be exactly 8192 bytes");
            Assert::AreEqual (kHgrPayloadSize, dhgrAuxPayload.size(),
                L"dhgr-cassowary-aux.bin must be exactly 8192 bytes");
            Assert::AreEqual (kHgrPayloadSize, dhgrMainPayload.size(),
                L"dhgr-cassowary-main.bin must be exactly 8192 bytes");
            Assert::AreEqual (kHgrPayloadSize, monoAuxPayload.size(),
                L"dhgr-cassowary-mono-aux.bin must be exactly 8192 bytes");
            Assert::AreEqual (kHgrPayloadSize, monoMainPayload.size(),
                L"dhgr-cassowary-mono-main.bin must be exactly 8192 bytes");

            Assembler       assembler (cpu.GetInstructionSet());

            asmResult = assembler.Assemble (source);
            if (!asmResult.success)
            {
                wchar_t  msg[256] = {};
                const char *  firstError = asmResult.errors.empty()
                    ? "(no error message)"
                    : asmResult.errors[0].message.c_str();
                swprintf_s (msg, L"casso-rocks.a65 must assemble cleanly. First "
                                 L"error: %hs", firstError);
                Assert::Fail (msg);
            }

            stage2Result = assembler.Assemble (stage2Source);
            if (!stage2Result.success)
            {
                wchar_t  msg[256] = {};
                const char *  firstError = stage2Result.errors.empty()
                    ? "(no error message)"
                    : stage2Result.errors[0].message.c_str();
                swprintf_s (msg, L"casso-rocks-stage2.a65 must assemble cleanly. "
                                 L"First error: %hs", firstError);
                Assert::Fail (msg);
            }

            Assert::AreEqual (Word (kDemoEntry), asmResult.startAddress,
                L"Stage 1 must be assembled with .org $0801 (boot ROM JMP target)");
            Assert::IsTrue (asmResult.bytes.size() > 0 &&
                            asmResult.bytes.size() <= kSectorByteSize - 1,
                L"Stage 1 code must fit in the remainder of sector 0 ($0801-$08FF)");
            Assert::AreEqual (Word (kStage2Entry), stage2Result.startAddress,
                L"Stage 2 must be assembled with .org $0A00");
            Assert::IsTrue (stage2Result.bytes.size() > 0 &&
                            stage2Result.bytes.size() <=
                                kStage2Sectors * kSectorByteSize,
                L"Stage 2 code must fit in the sectors reserved for it");

            // Build a 143360-byte raw .dsk image:
            //   - File offset 1..N (track 0 sector 0 minus the first byte):
            //     stage 1 boot code.
            //   - Tracks 1+2: 8 KB DHGR MONO aux half (loaded by stage 1
            //     into main $6000-$7FFF, then copied to aux $2000 by
            //     enter_dhgr).
            //   - Track 3 physical sectors 0..2: stage 2 code (lands at
            //     $1000-$12FF). The rest of track 3 is unused now that the
            //     LoRes pattern has gone, so stage 2 has room to grow
            //     without moving anything else.
            //   - Tracks 4+5: 8 KB DHGR MONO main half (loaded by stage 2
            //     init into main $8000-$9FFF, then copied to main $2000
            //     by enter_dhgr).
            //   - Tracks 6+7: 8 KB HGR MONO cassowary, loaded by the
            //     background phase to main $4000-$5FFF, which IS HGR page
            //     2 -- so mode 1 is a PAGE2 flip with no copy.
            //   - Tracks 8+9 and 10+11: the COLOR DHGR cassowary's aux and
            //     main halves, loaded by the background phase back into
            //     main $6000 and main $8000 -- the same staging the
            //     monochrome halves were copied out of, which is why mode
            //     2 is just a second enter_dhgr call over the same
            //     addresses.
            //   - Tracks 12+13: 8 KB HGR COLOR cassowary (loaded by stage 2
            //     background phase directly into its stash location at
            //     main $A000-$BFFF; mode_hgr_color memcpys to $2000).
            //
            //   Track order is cycle order: the first mode's data is
            //   physically earliest so first frame lands after ~5 disk
            //   reads rather than all 13, and each later mode's data is
            //   the next thing to arrive.
            //
            //   The payloads go through the DOS 3.3 physical-to-file
            //   interleave so that page S of a payload sits under address
            //   mark S: the demo's RWTS reads sectors in whatever order they
            //   arrive and files each by its address-mark number, so the
            //   sector the drive presents as S must hold
            //   payload[((T-startTrack)*16+S)*256..].
            static constexpr int  kDsk_PhysicalToFile[16] =
            {
                0, 7, 14, 6, 13, 5, 12, 4, 11, 3, 10, 2, 9, 1, 8, 15
            };

            std::vector<Byte>  raw (NibblizationLayer::kImageByteSize, 0);

            for (size_t i = 0; i < asmResult.bytes.size(); i++)
            {
                raw[1 + i] = asmResult.bytes[i];
            }

            // Track 3 physical sectors 0-2 -> stage 2 code at $1000-$12FF.
            // Route through the interleave so each payload page sits under
            // the address mark stage 1's RWTS will file it by.
            auto StampTrack3Sector = [&] (int physicalSector,
                                          const Byte * data, size_t len)
            {
                size_t  fileOffset = static_cast<size_t> (
                    3 * kSectorsPerTrack + kDsk_PhysicalToFile[physicalSector])
                    * kSectorByteSize;
                for (size_t i = 0; i < len; i++)
                {
                    raw[fileOffset + i] = data[i];
                }
            };

            // Stage 2 spans two sectors now, and the interleave puts them
            // nowhere near each other in the file, so each is stamped at
            // its own address mark rather than written as one run.
            for (int sector = 0; sector < kStage2Sectors; sector++)
            {
                size_t  offset    = static_cast<size_t> (sector) * kSectorByteSize;
                size_t  remaining = 0;

                if (offset >= stage2Result.bytes.size())
                {
                    break;
                }

                remaining = stage2Result.bytes.size() - offset;

                StampTrack3Sector (sector,
                                   stage2Result.bytes.data() + offset,
                                   remaining < kSectorByteSize ? remaining
                                                               : kSectorByteSize);
            }

            // Stitch a payload across 2 tracks starting at startTrack.
            auto StitchPayload = [&raw] (int startTrack,
                                         const std::vector<Byte> & payload)
            {
                for (int trackOffset = 0; trackOffset < 2; trackOffset++)
                {
                    int  track = startTrack + trackOffset;

                    for (int sector = 0; sector < kSectorsPerTrack; sector++)
                    {
                        size_t  fileOffset =
                            static_cast<size_t> (track * kSectorsPerTrack + kDsk_PhysicalToFile[sector])
                            * kSectorByteSize;
                        size_t  payloadOffset =
                            static_cast<size_t> (trackOffset * kSectorsPerTrack + sector)
                            * kSectorByteSize;

                        for (size_t i = 0; i < kSectorByteSize; i++)
                        {
                            raw[fileOffset + i] = payload[payloadOffset + i];
                        }
                    }
                }
            };

            StitchPayload (1,  monoAuxPayload);       // tracks 1+2   -> DHGR mono aux @ main $6000
            StitchPayload (4,  monoMainPayload);      // tracks 4+5   -> DHGR mono main @ main $8000
            StitchPayload (6,  hgrMonoPayload);       // tracks 6+7   -> HGR mono @ main $4000 (HGR page 2)
            StitchPayload (8,  dhgrAuxPayload);       // tracks 8+9   -> DHGR color aux @ main $6000
            StitchPayload (10, dhgrMainPayload);      // tracks 10+11 -> DHGR color main @ main $8000
            StitchPayload (12, hgrPayload);           // tracks 12+13 -> HGR color @ main $A000


            hr = host.BuildApple2eWithDisk2 (core);
            AssertSucceeded (hr, L"BuildApple2eWithDisk2 must succeed");

            core.PowerCycle();

            hr = core.diskStore->MountFromBytes (6, 0, "casso-rocks.dsk",
                                                 DiskFormat::Dsk, raw);
            AssertSucceeded (hr, L"MountFromBytes must succeed");

            img = core.diskStore->GetImage (6, 0);
            Assert::IsNotNull (img);
            core.diskController->SetExternalDisk (0, img);

            // The cheap questions, asked of the container the drive is
            // actually holding and before a processor is involved. The demo's
            // RWTS reads thirteen tracks by address field and there is no
            // operating system underneath it to report a bad read, so a
            // stitched image the drive does not present verbatim is not a
            // wrong picture -- it is a processor loaded with data.
            GuestSession::AssertTheDrivePresentsWhatWasMounted (
                *img, raw, L"the assembled demo disk");
            GuestSession::AssertTheDriveCanReadTheBootSector (
                *img, L"the assembled demo disk");

            //  NOTHING POINTS THE PROCESSOR ANYWHERE. PowerCycle leaves it
            //  on the //e's own reset vector, so the ROM runs the power-on
            //  and boots the disk itself: it installs CSW and KSW, writes
            //  the break vector, the soft-entry vector at $03F2 and the
            //  power-up byte at $03F4 from its own table, and then scans
            //  the slots and finds the Disk II.
            //
            //  This used to jump straight into the boot PROM at $C600 with
            //  the two hooks poked in by hand, which is three or four
            //  bytes' worth of a power-on and made the harness useless for
            //  the one thing the demo does at the end: hand the machine
            //  back. With no power-up byte the reset handler always took
            //  its cold path and re-booted slot 6, so an exit that worked
            //  and an exit that crashed looked identical from here, and
            //  the exit bugs were all found by hand in the emulator
            //  instead. Booting the way the machine does costs about
            //  200k cycles.
            core.RunCycles (kDemoCycleBudget);

            // BOOT LANDING IS THE QUESTION, NOT A PICTURE. Nothing can
            // detect the monitor -- no Apple II can, the video connectors
            // are output only -- so the demo asks, and waits in TEXT until
            // it is answered. Everything is loaded by then, which is the
            // point of asking first: the disk works behind the question.
            ss = core.softSwitches.get();

            Assert::IsNotNull (ss, L"Apple2eSoftSwitchBank must be present");
            Assert::IsFalse (ss->IsGraphicsMode(),
                L"Demo must wait in TEXT mode until the question is answered");

            //  The question itself, at row 11 column 4 ($05AC). Stored in
            //  the source as plain ASCII -- so that as65 and Merlin emit
            //  identical bytes for it -- and OR'd to high ASCII as it is
            //  written, which is what the text screen displays as normal
            //  (non-inverse, non-flashing) characters.
            {
                const char *  expected = "WHICH MONITOR ARE YOU USING?";

                for (size_t i = 0; expected[i] != '\0'; i++)
                {
                    Byte  want   = static_cast<Byte> (expected[i]) | 0x80;
                    Byte  actual = core.bus->ReadByte (
                        static_cast<Word> (0x05AC + i));

                    if (actual != want)
                    {
                        wchar_t  msg[256] = {};
                        swprintf_s (msg, L"Monitor question mismatch at $%04X: "
                                         L"expected $%02X, got $%02X.",
                                    static_cast<unsigned> (0x05AC + i),
                                    static_cast<unsigned> (want),
                                    static_cast<unsigned> (actual));
                        Assert::Fail (msg);
                    }
                }
            }

            //  Answer M. The monochrome halves were staged into the
            //  framebuffer during the load phase, so this is only the
            //  display switches, and the picture is there immediately.
            Assert::IsNotNull (core.keyboard.get(), L"AppleKeyboard must be present");
            core.keyboard->PressKey ('M');
            core.RunCycles (200'000ULL);

            Assert::IsTrue (ss->IsGraphicsMode(),
                L"Answering M must leave the //e in graphics mode (TEXT off)");
            Assert::IsFalse (ss->IsMixedMode(),
                L"Answering M must leave MIXED off (full-screen graphics)");
            Assert::IsFalse (ss->IsPage2(),
                L"Mode 0 (DHGR mono) must select PAGE1");
            Assert::IsTrue (ss->IsHiresMode(),
                L"Mode 0 (DHGR mono) must enable HIRES");

            // Verify framebuffer contents at boot landing.
            //
            // Stage 1 stages the monochrome aux half at $6000; stage 2
            // loads the monochrome main half to $8000 and stage_dhgr
            // copies both into the framebuffer -- copies only, the screen
            // is still showing the question. The load phase then puts the
            // HGR monochrome image on page 2 and the COLOR halves back
            // over that staging. So by the time the question is answered:
            //
            //   main $2000 = mono DHGR main    aux $2000 = mono DHGR aux
            //   main $4000 = mono HGR          main $6000 = color DHGR aux
            //   main $8000 = color DHGR main   main $A000 = color HGR
            //
            // The staging holding the color halves rather than the
            // monochrome ones is the whole mechanism behind mode 2 costing
            // no memory, so it is asserted rather than assumed.
            auto VerifyMemRange = [&] (Word baseAddr,
                                       const std::vector<Byte> & expected,
                                       const wchar_t * label)
            {
                size_t  mismatchCount      = 0;
                size_t  firstMismatch      = 0;
                Byte    expectedAtMismatch = 0;
                Byte    actualAtMismatch   = 0;

                for (size_t i = 0; i < kHgrPayloadSize; i++)
                {
                    Byte  e = expected[i];
                    Byte  actual = core.bus->ReadByte (
                        static_cast<Word> (baseAddr + i));

                    if (actual != e)
                    {
                        if (mismatchCount == 0)
                        {
                            firstMismatch       = i;
                            expectedAtMismatch  = e;
                            actualAtMismatch    = actual;
                        }

                        mismatchCount++;
                    }
                }

                if (mismatchCount != 0)
                {
                    wchar_t  msg[256] = {};
                    swprintf_s (msg, L"%ls memory mismatch: %zu of %zu bytes "
                                     L"differ. First at $%04X: expected $%02X, "
                                     L"got $%02X.",
                                label,
                                mismatchCount,
                                kHgrPayloadSize,
                                static_cast<unsigned> (baseAddr + firstMismatch),
                                static_cast<unsigned> (expectedAtMismatch),
                                static_cast<unsigned> (actualAtMismatch));
                    Assert::Fail (msg);
                }
            };

            VerifyMemRange (0x2000, monoMainPayload,
                L"DHGR mono main half at boot landing (main $2000)");
            VerifyMemRange (0x4000, hgrMonoPayload,
                L"HGR mono cassowary on HGR page 2 (main $4000)");
            VerifyMemRange (0x6000, dhgrAuxPayload,
                L"DHGR color aux half over the staging (main $6000)");
            VerifyMemRange (0x8000, dhgrMainPayload,
                L"DHGR color main half over the staging (main $8000)");
            VerifyMemRange (0xA000, hgrPayload,
                L"Stashed HGR color cassowary (main $A000)");

            // The DHGR aux half is at aux $2000 — read via MMU aux buffer.
            auxBuf = core.mmu->GetAuxBuffer();
            Assert::IsNotNull (auxBuf, L"MMU aux buffer must be available");
            {
                size_t  m = 0;
                for (size_t i = 0; i < kHgrPayloadSize; i++)
                {
                    if (auxBuf[0x2000 + i] != monoAuxPayload[i]) { m++; }
                }

                Assert::AreEqual (size_t (0), m,
                    L"DHGR mono aux half at boot landing must match payload");
            }

            //  THE ANSWER SELECTS THE PAIR. A monochrome answer shows the
            //  monochrome images and nothing else -- three steps, then
            //  round again. The color images stay loaded the whole time
            //  and simply never appear, which is what the mode 2 / mode 3
            //  assertions below the re-boot are for.

            // Step 1 -> HGR monochrome. No copy: the image was loaded onto
            // HGR page 2 and the step is a PAGE2 flip out of DHGR, so what
            // is asserted is the switch state and that page 2 still holds
            // the image.
            core.keyboard->PressKey (' ');
            core.RunCycles (200'000ULL);
            Assert::IsTrue (ss->IsHiresMode(),
                L"Step 1 (HGR mono) must keep HIRES on");
            Assert::IsTrue (ss->IsPage2(),
                L"Step 1 (HGR mono) must select PAGE2, where the image is");
            Assert::IsTrue (ss->IsGraphicsMode(),
                L"Step 1 (HGR mono) must keep TEXT off");
            VerifyMemRange (0x4000, hgrMonoPayload,
                L"HGR mono cassowary still on page 2 at step 1");

            //  Step 2, the hi-res color-mask sweep: HGR, then POKE 228
            //  / HPLOT 0,0 / CALL -3082 round and round until a key. Two
            //  things are worth asserting and one is not. The mask
            //  counter advancing proves the loop is running, and $E4 is
            //  exact, so that is checked rather than eyeballing pixels.
            //  The page no longer matching what step 1 left proves BKGND
            //  is actually painting. What is NOT checked is the fill's
            //  content: it is mid-flight at any given cycle, and
            //  Applesoft_HgrColorSweep_AllMasksMatchRomFill below already
            //  models what BKGND paints, mask by mask, against the ROM.
            core.keyboard->PressKey (' ');
            core.RunCycles (1'500'000ULL);

            Assert::IsTrue (ss->IsHiresMode(),
                L"Step 2 (sweep) must turn HIRES on");
            Assert::IsTrue (ss->IsGraphicsMode(),
                L"Step 2 (sweep) must keep TEXT off");
            Assert::IsFalse (ss->IsMixedMode(),
                L"Step 2 (sweep) must clear the MIXED that HGR sets");
            Assert::IsFalse (ss->IsPage2(),
                L"Step 2 (sweep) paints hi-res page 1");

            {
                Byte    mask   = core.bus->ReadByte (0x0048);
                size_t  intact = 0;

                for (size_t i = 0; i < kHgrPayloadSize; i++)
                {
                    if (core.bus->ReadByte (static_cast<Word> (0x2000 + i))
                        == hgrMonoPayload[i])
                    {
                        intact++;
                    }
                }

                Assert::IsTrue (intact < kHgrPayloadSize,
                    L"the sweep must paint over what step 1 left on the page");

                core.RunCycles (1'500'000ULL);

                Assert::AreNotEqual (mask, core.bus->ReadByte (0x0048),
                    L"the sweep's mask counter must keep advancing, or the "
                    L"sweep has stopped sweeping");
            }

            quietMark = core.speaker->GetToggleTimestamps().size();
            core.keyboard->PressKey (' ');
            core.RunCycles (500'000ULL);
            //  IT HAS TO LEAVE THE VIDEO HARDWARE HABITABLE. The reset
            //  handler does not clear 80COL, so exiting from a DHGR step
            //  dropped into Applesoft with the 80-column hardware on and
            //  the 80-column firmware not hooked up to match -- half-width
            //  glyphs, and typing that misbehaves. do_exit sets the mode
            //  explicitly now, and this is the guard on that.
            Assert::IsFalse (ss->IsGraphicsMode(),
                L"do_exit must leave TEXT on");
            Assert::IsFalse (ss->Is80ColMode(),
                L"do_exit must leave 80COL off -- 40-column text is what "
                L"Applesoft is about to write into");
            Assert::IsFalse (ss->Is80Store(),
                L"do_exit must leave 80STORE off");
            Assert::IsFalse (ss->IsDoubleHiRes(),
                L"do_exit must leave DHIRES off");
            Assert::IsFalse (ss->IsPage2(),
                L"do_exit must leave PAGE1 selected");

            //  AND IT HAS TO HAND OVER A LIVE APPLESOFT, with the sign-off
            //  still on the screen under it. Both halves are the point:
            //  the demo wipes the text page and writes its own last line
            //  while the picture is still up, and Applesoft's cold start
            //  leaves the screen alone, so what the user is left looking
            //  at is the sign-off with a prompt below it rather than
            //  whatever the demo happened to leave in text memory.
            AssertSignedOffToBasic (core, L"the monochrome route", quietMark);

            //  THE OTHER ANSWER, on the same mounted disk. Re-boot and say
            //  C instead: a different pair of images, reached by re-staging
            //  the framebuffer out of the staging areas the load phase left
            //  holding the color halves. This is the half of the feature the
            //  M path never exercises -- and the half where the wrap has to
            //  do real work rather than just re-issuing switches.
            //  A power cycle drops what the drive was holding and hands
            //  out fresh MMU buffers, so the disk has to be re-bound and
            //  every cached pointer re-fetched before the second boot.
            core.PowerCycle();
            core.diskController->SetExternalDisk (0, img);
            ss     = core.softSwitches.get();
            auxBuf = core.mmu->GetAuxBuffer();
            Assert::IsNotNull (ss,     L"soft switches must survive the re-boot");
            Assert::IsNotNull (auxBuf, L"aux buffer must survive the re-boot");

            core.RunCycles (kDemoCycleBudget);

            Assert::IsFalse (ss->IsGraphicsMode(),
                L"The re-booted demo must wait in TEXT for its answer too");

            core.keyboard->PressKey ('C');
            core.RunCycles (600'000ULL);

            Assert::IsTrue (ss->IsGraphicsMode(),
                L"Answering C must leave the //e in graphics mode");
            Assert::IsFalse (ss->IsPage2(),
                L"Mode 2 (DHGR color) must select PAGE1");
            Assert::IsTrue (ss->IsHiresMode(),
                L"Mode 2 (DHGR color) must enable HIRES");

            VerifyMemRange (0x2000, dhgrMainPayload,
                L"DHGR color main half at main $2000 after answering C");
            {
                size_t  m = 0;
                for (size_t i = 0; i < kHgrPayloadSize; i++)
                {
                    if (auxBuf[0x2000 + i] != dhgrAuxPayload[i]) { m++; }
                }

                Assert::AreEqual (size_t (0), m,
                    L"DHGR color aux half must reach aux $2000 after answering C");
            }

            // Step 1 on the color answer is the HGR color cassowary,
            // restored from the main $A000 stash to page 1.
            core.keyboard->PressKey (' ');
            core.RunCycles (300'000ULL);
            Assert::IsTrue (ss->IsHiresMode(),
                L"Step 1 (HGR color) must keep HIRES on");
            Assert::IsFalse (ss->IsPage2(),
                L"Step 1 (HGR color) must select PAGE1");
            VerifyMemRange (0x2000, hgrPayload,
                L"HGR color cassowary restored to main $2000 at step 1");

            //  AND THE MONOCHROME IMAGES ARE NOT IN THIS CYCLE. Page 2
            //  still holds the monochrome HGR image, resident and never
            //  selected -- which is the difference between the answer
            //  filtering the cycle and merely choosing where it starts.
            VerifyMemRange (0x4000, hgrMonoPayload,
                L"the monochrome HGR image stays loaded but unvisited");

            //  Step 2, the hi-res color-mask sweep: HGR, then POKE 228
            //  / HPLOT 0,0 / CALL -3082 round and round until a key. Two
            //  things are worth asserting and one is not. The mask
            //  counter advancing proves the loop is running, and $E4 is
            //  exact, so that is checked rather than eyeballing pixels.
            //  The page no longer matching what step 1 left proves BKGND
            //  is actually painting. What is NOT checked is the fill's
            //  content: it is mid-flight at any given cycle, and
            //  Applesoft_HgrColorSweep_AllMasksMatchRomFill below already
            //  models what BKGND paints, mask by mask, against the ROM.
            core.keyboard->PressKey (' ');
            core.RunCycles (1'500'000ULL);

            Assert::IsTrue (ss->IsHiresMode(),
                L"Step 2 (sweep) must turn HIRES on");
            Assert::IsTrue (ss->IsGraphicsMode(),
                L"Step 2 (sweep) must keep TEXT off");
            Assert::IsFalse (ss->IsMixedMode(),
                L"Step 2 (sweep) must clear the MIXED that HGR sets");
            Assert::IsFalse (ss->IsPage2(),
                L"Step 2 (sweep) paints hi-res page 1");

            {
                Byte    mask   = core.bus->ReadByte (0x0048);
                size_t  intact = 0;

                for (size_t i = 0; i < kHgrPayloadSize; i++)
                {
                    if (core.bus->ReadByte (static_cast<Word> (0x2000 + i))
                        == hgrPayload[i])
                    {
                        intact++;
                    }
                }

                Assert::IsTrue (intact < kHgrPayloadSize,
                    L"the sweep must paint over what step 1 left on the page");

                core.RunCycles (1'500'000ULL);

                Assert::AreNotEqual (mask, core.bus->ReadByte (0x0048),
                    L"the sweep's mask counter must keep advancing, or the "
                    L"sweep has stopped sweeping");
            }

            //  ESC, the other way out, and from a different mode than the
            //  monochrome path used. Both routes run the same do_exit, and
            //  what matters is that it leaves the same habitable screen
            //  whichever step it was called from.
            quietMark = core.speaker->GetToggleTimestamps().size();
            core.keyboard->PressKey (0x1B);
            core.RunCycles (200'000ULL);
            //  IT HAS TO LEAVE THE VIDEO HARDWARE HABITABLE. The reset
            //  handler does not clear 80COL, so exiting from a DHGR step
            //  dropped into Applesoft with the 80-column hardware on and
            //  the 80-column firmware not hooked up to match -- half-width
            //  glyphs, and typing that misbehaves. do_exit sets the mode
            //  explicitly now, and this is the guard on that.
            Assert::IsFalse (ss->IsGraphicsMode(),
                L"do_exit must leave TEXT on");
            Assert::IsFalse (ss->Is80ColMode(),
                L"do_exit must leave 80COL off -- 40-column text is what "
                L"Applesoft is about to write into");
            Assert::IsFalse (ss->Is80Store(),
                L"do_exit must leave 80STORE off");
            Assert::IsFalse (ss->IsDoubleHiRes(),
                L"do_exit must leave DHIRES off");
            Assert::IsFalse (ss->IsPage2(),
                L"do_exit must leave PAGE1 selected");

            AssertSignedOffToBasic (core, L"the ESC route out of the color "
                                          L"cycle", quietMark);

            //  NOTHING HERE TOUCHES THE TRACKED IMAGE, IN EITHER DIRECTION.
            //
            //  This used to WRITE Apple2/Demos/casso-rocks.dsk with the image
            //  it had just built, on every run, called out as a deliberate
            //  side effect. It normally wrote the same bytes back, so git
            //  stayed clean and the only trace was a moved mtime -- until a
            //  run that built a different image and left a corrupted binary
            //  asset in the tree.
            //
            //  Replacing the write with a READ of the same file was still
            //  wrong. A test that fails because a checked-in artifact is stale
            //  is a test reporting on the state of the machine it is running
            //  on, and this one would fail on a tree that is perfectly
            //  correct except that somebody has not re-run a script.
            //
            //  WHETHER THE COMMITTED DISK IS UP TO DATE IS A BUILD QUESTION,
            //  and it is asked where the disk is built:
            //  `scripts/BuildDemoDisk.ps1 -Verify` rebuilds it and compares
            //  without writing. What this test is for is upstream of that --
            //  the demo assembles, boots, and paints what it should -- and it
            //  has already asserted all of it above, from an image held in
            //  memory and never written down.
        }
    }


    ////////////////////////////////////////////////////////////////////////////
    //
    //  Applesoft hi-res color-mask sweep
    //
    //  Companion gate to the demo-disk boot test above, covering the far
    //  end of the same hi-res pipeline: the Applesoft ROM's own hi-res
    //  package rather than a hand-written RWTS.
    //
    //  The Applesoft one-liner
    //
    //      HGR : FOR J=0 TO 255 : POKE 228,J : HPLOT 0,0 : CALL -3082 : NEXT
    //
    //  walks all 256 raw color masks. `HCOLOR=` can only reach the eight
    //  masks in the ROM table at $F6F6 (00 2A 55 7F 80 AA D5 FF); poking
    //  228 ($E4) reaches every one, which makes the sweep an exhaustive
    //  pass over the hi-res renderer's whole input space -- each 7-bit
    //  pixel pattern against both palette (high-bit) states -- presented
    //  as stable, full-screen, uniform fields where a wrong artifact
    //  color is unmissable.
    //
    //  Two ROM details the sweep depends on, both asserted below:
    //
    //    - $F450 is the ONLY read of location 228 in the entire 16 KB
    //      ROM. It copies $E4 into the working color at $1C, and the
    //      fill routine paints from $1C. The HPLOT is therefore not
    //      decorative -- it is the sole bridge from the poke to the
    //      screen. Without it the sweep paints 256 identical black
    //      frames.
    //    - x = 0 lands in byte 0 of the scanline, an even byte, so the
    //      phase-advance branch at $F454 is not taken and $1C receives
    //      the mask verbatim instead of phase-flipped.
    //
    ////////////////////////////////////////////////////////////////////////////

    // Applesoft hi-res ROM entry points (Apple //e ROM image, $C000-$FFFF).
    static constexpr Word      kRomHgr              = 0xF3E2;   // HGR: page 1, MIXED on
    static constexpr Word      kRomHplot0           = 0xF457;   // plot (X/Y, A) using $E4
    static constexpr Word      kRomBkgnd            = 0xF3F6;   // CALL -3082: fill from $1C

    // Applesoft hi-res zero page.
    static constexpr Word      kZpWorkColor         = 0x001C;   // the byte BKGND paints
    static constexpr Word      kZpColorMask         = 0x00E4;   // 228: what HCOLOR= writes
    static constexpr Word      kZpHiresPage         = 0x00E6;   // $20 page 1, $40 page 2

    static constexpr Word      kHiresPage1Base      = 0x2000;
    static constexpr Word      kHiresPage1LastByte  = 0x3FFF;
    static constexpr Byte      kHiresPage1High      = 0x20;
    static constexpr size_t    kHiresPageBytes      = 8192;
    static constexpr size_t    kColorMaskCount      = 256;
    static constexpr Byte      kLastColorMask       = 0xFF;

    // The phase-advance helper at $F47C/$F47E inverts the seven pixel
    // bits between bytes only when the mask's pixel bits land in this
    // range -- exactly the masks whose pattern does not tile evenly
    // across a 7-pixel byte. The range is symmetric under 7-bit
    // complement, so a qualifying mask toggles stably rather than
    // drifting.
    static constexpr Byte      kMaskPixelBits       = 0x7F;
    static constexpr Byte      kFlipRangeFirst      = 0x20;
    static constexpr Byte      kFlipRangeLast       = 0x5F;

    // Harness stubs, planted in the $0300 free space below the //e's
    // page-3 vectors.
    static constexpr Word      kSweepStubBase       = 0x0300;
    static constexpr Word      kSweepStubMaskAt     = 0x0301;   // patched per mask
    static constexpr Word      kSweepStubDone       = 0x0310;
    static constexpr Word      kHgrStubBase         = 0x0320;
    static constexpr Word      kHgrStubDone         = 0x0323;

    static constexpr Byte      kOpLdaImm            = 0xA9;
    static constexpr Byte      kOpStaZp             = 0x85;
    static constexpr Byte      kOpLdxImm            = 0xA2;
    static constexpr Byte      kOpLdyImm            = 0xA0;
    static constexpr Byte      kOpJsrAbs            = 0x20;
    static constexpr Byte      kOpJmpAbs            = 0x4C;

    static constexpr Word      kByteMask            = 0x00FF;
    static constexpr int       kByteShift           = 8;

    // 1.0205 MHz: the //e's effective CPU rate once the long-cycle
    // stretch is folded in. Used only to report the sweep in seconds.
    static constexpr double    kCpuClockHz          = 1020484.0;

    static constexpr uint64_t  kSweepColdBootCycles = 5'000'000ULL;
    static constexpr uint64_t  kOneFillCycleBudget  = 500'000ULL;
    static constexpr uint64_t  kSweepPollChunk      = 100'000ULL;
    static constexpr uint64_t  kSweepCycleCeiling   = 200'000'000ULL;

    static constexpr int       kFbWidth             = 560;
    static constexpr int       kFbHeight            = 384;

    // Golden hash over all 256 rendered color fields, captured from the
    // first deterministic run. Any change to NtscColorTable, the hi-res
    // scanline walk, or the framebuffer pixel layout moves it.
    static constexpr uint64_t  kSweepRenderHash     = 0xD883834A016C9325ULL;

    static constexpr const char *  kSweepOneLiner =
        "HGR : FOR J=0 TO 255 : POKE 228,J : HPLOT 0,0 : CALL -3082 : NEXT";


    ////////////////////////////////////////////////////////////////////////////
    //
    //  ExpectedFillByte
    //
    //  Independent model of what BKGND ($F3F6) paints, derived from the
    //  routine rather than captured from it. BKGND writes the working
    //  color at every byte of the 8 KB page and calls the phase-advance
    //  helper after each one, so a mask whose pixel bits fall in
    //  $20-$5F alternates mask / mask^$7F down the page and every other
    //  mask paints uniformly. Byte 0 always gets the mask itself.
    //
    ////////////////////////////////////////////////////////////////////////////

    static Byte ExpectedFillByte (Byte mask, size_t byteIndex)
    {
        Byte  pixelBits = static_cast<Byte> (mask & kMaskPixelBits);
        Byte  expected  = 0;
        bool   alternates = (pixelBits >= kFlipRangeFirst) &&
                            (pixelBits <= kFlipRangeLast);
        expected = mask;



        // Only the odd bytes of an alternating mask differ; byte 0 (and every
        // byte of a non-alternating mask) is the mask itself.
        if (alternates && ((byteIndex & 1) != 0))
        {
            expected = static_cast<Byte> (mask ^ kMaskPixelBits);
        }

        return expected;
    }


    ////////////////////////////////////////////////////////////////////////////
    //
    //  RunUntilPc
    //
    //  Steps the CPU until the program counter reaches `stopPc` or the
    //  cycle budget is exhausted, mirroring EmulatorCore::RunCycles'
    //  step/accumulate pairing. Returns the cycles actually consumed so
    //  callers can time an individual ROM call.
    //
    ////////////////////////////////////////////////////////////////////////////

    static uint64_t RunUntilPc (EmulatorCore & core, Word stopPc, uint64_t cycleBudget)
    {
        uint64_t   startCycles = core.cpu->GetTotalCycles();
        uint64_t   spent       = 0;
        uint32_t   stepCycles  = 0;



        while (spent < cycleBudget)
        {
            if (core.cpu->GetPC() == stopPc)
            {
                break;
            }

            core.cpu->StepOne();
            stepCycles = core.cpu->GetLastInstructionCycles();
            core.cpu->AddCycles (stepCycles);
            spent = core.cpu->GetTotalCycles() - startCycles;
        }

        return spent;
    }


    ////////////////////////////////////////////////////////////////////////////
    //
    //  PlantBytes
    //
    ////////////////////////////////////////////////////////////////////////////

    static void PlantBytes (EmulatorCore & core, Word base, const Byte * code, size_t len)
    {
        size_t   i = 0;



        for (i = 0; i < len; i++)
        {
            core.bus->WriteByte (static_cast<Word> (base + i), code[i]);
        }
    }


    ////////////////////////////////////////////////////////////////////////////
    //
    //  LowByte / HighByte
    //
    ////////////////////////////////////////////////////////////////////////////

    static Byte LowByte  (Word value) { return static_cast<Byte> (value & kByteMask); }
    static Byte HighByte (Word value) { return static_cast<Byte> (value >> kByteShift); }


    ////////////////////////////////////////////////////////////////////////////
    //
    //  PlantHgrStub — JSR $F3E2 then park on a self-JMP the test can poll.
    //
    ////////////////////////////////////////////////////////////////////////////

    static void PlantHgrStub (EmulatorCore & core)
    {
        const Byte   code[] =
        {
            kOpJsrAbs, LowByte (kRomHgr),      HighByte (kRomHgr),
            kOpJmpAbs, LowByte (kHgrStubDone), HighByte (kHgrStubDone)
        };



        PlantBytes (core, kHgrStubBase, code, sizeof (code));
    }


    ////////////////////////////////////////////////////////////////////////////
    //
    //  PlantSweepStub
    //
    //  One iteration of the Applesoft loop body, in 6502: store the mask
    //  into 228, HPLOT 0,0 (A = Y coordinate, X/Y = 16-bit X coordinate),
    //  then CALL -3082. Parks on a self-JMP so the test can detect the
    //  return without guessing a cycle count.
    //
    ////////////////////////////////////////////////////////////////////////////

    static void PlantSweepStub (EmulatorCore & core)
    {
        const Byte   code[] =
        {
            kOpLdaImm, 0,                                           // patched per mask
            kOpStaZp,  LowByte (kZpColorMask),
            kOpLdaImm, 0,                                           // hi-res Y coordinate
            kOpLdxImm, 0,                                           // X coordinate low
            kOpLdyImm, 0,                                           // X coordinate high
            kOpJsrAbs, LowByte (kRomHplot0),     HighByte (kRomHplot0),
            kOpJsrAbs, LowByte (kRomBkgnd),      HighByte (kRomBkgnd),
            kOpJmpAbs, LowByte (kSweepStubDone), HighByte (kSweepStubDone)
        };



        PlantBytes (core, kSweepStubBase, code, sizeof (code));
    }


    ////////////////////////////////////////////////////////////////////////////
    //
    //  Fnv1a64 — stable framebuffer hash for the golden-render gate.
    //
    ////////////////////////////////////////////////////////////////////////////

    static uint64_t Fnv1a64 (uint64_t seed, const uint32_t * data, size_t count)
    {
        uint64_t   h = seed;
        size_t     i = 0;
        int        b = 0;
        uint32_t   v = 0;



        for (i = 0; i < count; i++)
        {
            v = data[i];

            for (b = 0; b < 4; b++)
            {
                h ^= static_cast<uint8_t> ((v >> (b * 8)) & kByteMask);
                h *= 0x100000001b3ULL;
            }
        }

        return h;
    }


    ////////////////////////////////////////////////////////////////////////////
    //
    //  VerifySweptPage — compares the whole hi-res page against the model
    //  for one mask, failing once with a located diff rather than 8192
    //  times.
    //
    ////////////////////////////////////////////////////////////////////////////

    static void VerifySweptPage (EmulatorCore & core, Byte mask)
    {
        size_t   byteIndex       = 0;
        size_t   mismatchCount   = 0;
        size_t   firstMismatch   = 0;
        Byte     expected        = 0;
        Byte     actual          = 0;
        Byte     expectedAtFirst = 0;
        Byte     actualAtFirst   = 0;
        wchar_t  msg[256]        = {};



        for (byteIndex = 0; byteIndex < kHiresPageBytes; byteIndex++)
        {
            expected = ExpectedFillByte (mask, byteIndex);
            actual   = core.bus->ReadByte (
                static_cast<Word> (kHiresPage1Base + byteIndex));

            if (actual == expected)
            {
                continue;
            }

            if (mismatchCount == 0)
            {
                firstMismatch   = byteIndex;
                expectedAtFirst = expected;
                actualAtFirst   = actual;
            }

            mismatchCount++;
        }

        if (mismatchCount != 0)
        {
            swprintf_s (msg, L"Mask $%02X: %zu of %zu page bytes differ from "
                             L"the BKGND model. First at $%04X: expected "
                             L"$%02X, got $%02X.",
                        static_cast<unsigned> (mask),
                        mismatchCount,
                        kHiresPageBytes,
                        static_cast<unsigned> (kHiresPage1Base + firstMismatch),
                        static_cast<unsigned> (expectedAtFirst),
                        static_cast<unsigned> (actualAtFirst));
            Assert::Fail (msg);
        }
    }


    ////////////////////////////////////////////////////////////////////////////
    //
    //  Drives the real ROM routines over all 256 color masks and checks
    //  every byte of the hi-res page against the independent model.
    //
    //  Exercises: Apple2e.rom Applesoft hi-res package -> 6502 CPU ->
    //  Apple2eMmu page-1 writes -> Apple2eSoftSwitchBank mode latching.
    //
    ////////////////////////////////////////////////////////////////////////////

    TEST_METHOD (Applesoft_HgrColorSweep_AllMasksMatchRomFill)
    {
        HeadlessHost   host;
        EmulatorCore   core;
        uint64_t       fillCycles      = 0;
        uint64_t       totalFillCycles = 0;
        uint64_t       minFillCycles   = UINT64_MAX;
        uint64_t       maxFillCycles   = 0;
        size_t         maskIndex       = 0;
        Byte           mask            = 0;

        HRESULT   hr = host.BuildApple2e (core);



        AssertSucceeded (hr, L"BuildApple2e must succeed");
        Assert::IsTrue (core.HasApple2e(), L"//e wiring must be complete");

        core.PowerCycle();
        core.RunCycles  (kSweepColdBootCycles);

        // HGR: select page 1, clear it, latch the display mode
        PlantHgrStub (core);
        core.cpu->SetPC (kHgrStubBase);
        fillCycles = RunUntilPc (core, kHgrStubDone, kOneFillCycleBudget);

        Assert::AreEqual (Word (kHgrStubDone), core.cpu->GetPC(),
            L"HGR ($F3E2) must return within the cycle budget");
        Assert::AreEqual (kHiresPage1High, core.bus->ReadByte (kZpHiresPage),
            L"HGR must set HPAG ($E6) to $20 (hi-res page 1)");
        Assert::IsTrue  (core.softSwitches->IsGraphicsMode(),
            L"HGR must clear TEXT");
        Assert::IsTrue  (core.softSwitches->IsHiresMode(),
            L"HGR must set HIRES");
        Assert::IsTrue  (core.softSwitches->IsMixedMode(),
            L"HGR (unlike HGR2) must leave MIXED on -- $F3E7 touches $C053, "
            L"so the bottom four text rows stay visible");
        Assert::IsFalse (core.softSwitches->IsPage2(),
            L"HGR must select PAGE1");

        // Sweep every raw color mask
        PlantSweepStub (core);

        for (maskIndex = 0; maskIndex < kColorMaskCount; maskIndex++)
        {
            mask = static_cast<Byte> (maskIndex);

            core.bus->WriteByte (kSweepStubMaskAt, mask);
            core.cpu->SetPC (kSweepStubBase);

            fillCycles = RunUntilPc (core, kSweepStubDone, kOneFillCycleBudget);

            Assert::AreEqual (Word (kSweepStubDone), core.cpu->GetPC(),
                L"HPLOT + BKGND must return within the cycle budget");

            totalFillCycles += fillCycles;

            if (fillCycles < minFillCycles) { minFillCycles = fillCycles; }
            if (fillCycles > maxFillCycles) { maxFillCycles = fillCycles; }

            // HPLOT copies 228 into the working color; 8192 phase flips
            // is an even number, so $1C lands back on the mask itself.
            Assert::AreEqual (mask, core.bus->ReadByte (kZpColorMask),
                L"The fill must not disturb the poked mask at 228 ($E4)");
            Assert::AreEqual (mask, core.bus->ReadByte (kZpWorkColor),
                L"HPLOT 0,0 must copy 228 into the working color at $1C "
                L"verbatim (byte 0 is even, so no phase flip)");

            VerifySweptPage (core, mask);
        }

        Logger::WriteMessage (std::format (
            "HGR color sweep: {} masks, {} ROM cycles total "
            "({:.2f} s emulated), per fill min {} / max {} cycles "
            "({:.3f} / {:.3f} s).\n",
            kColorMaskCount,
            totalFillCycles,
            static_cast<double> (totalFillCycles) / kCpuClockHz,
            minFillCycles,
            maxFillCycles,
            static_cast<double> (minFillCycles) / kCpuClockHz,
            static_cast<double> (maxFillCycles) / kCpuClockHz).c_str());
    }


    ////////////////////////////////////////////////////////////////////////////
    //
    //  Renders all 256 modeled color-mask fields through AppleHiResMode
    //  and folds every frame into one FNV-1a-64 hash. The fields come
    //  from the model (validated against the real ROM by the test above),
    //  so this isolates the NTSC artifact renderer: any palette
    //  inversion, half-dot-shift error, or byte-boundary phase bug moves
    //  the hash.
    //
    ////////////////////////////////////////////////////////////////////////////

    TEST_METHOD (Applesoft_HgrColorSweep_RendersDeterministicFrames)
    {
        HeadlessHost  host;
        EmulatorCore  core;
        uint64_t      hash      = 0;
        size_t        maskIndex = 0;
        size_t        byteIndex = 0;
        Byte          mask      = 0;
        HRESULT       hr        = S_OK;
        std::vector<uint32_t>   fb (static_cast<size_t> (kFbWidth) * kFbHeight, 0);
        hash = 0xcbf29ce484222325ULL;

        hr = host.BuildApple2e (core);



        AssertSucceeded (hr, L"BuildApple2e must succeed");
        Assert::IsTrue (core.HasApple2e(), L"//e wiring must be complete");

        core.PowerCycle();
        core.RunCycles  (kSweepColdBootCycles);

        AppleHiResMode   hires (*core.bus);

        hires.SetPage2 (false);

        for (maskIndex = 0; maskIndex < kColorMaskCount; maskIndex++)
        {
            mask = static_cast<Byte> (maskIndex);

            for (byteIndex = 0; byteIndex < kHiresPageBytes; byteIndex++)
            {
                core.bus->WriteByte (
                    static_cast<Word> (kHiresPage1Base + byteIndex),
                    ExpectedFillByte (mask, byteIndex));
            }

            hires.Render (nullptr, fb.data(), kFbWidth, kFbHeight);
            hash = Fnv1a64 (hash, fb.data(), fb.size());
        }

        Logger::WriteMessage (std::format (
            "HGR color sweep render hash: 0x{:016X}\n", hash).c_str());

        Assert::AreEqual (kSweepRenderHash, hash, std::format (
            L"Color-sweep render hash mismatch: got 0x{:016X}", hash).c_str());
    }


    ////////////////////////////////////////////////////////////////////////////
    //
    //  Types the actual Applesoft one-liner at the `]` prompt and runs it
    //  to completion, measuring how long the full 256-step sweep takes on
    //  a real //e. Covers the path the ROM-driven test above skips:
    //  Applesoft tokenizing, FOR/NEXT, POKE and CALL argument
    //  evaluation, and the HPLOT statement handler.
    //
    ////////////////////////////////////////////////////////////////////////////

    TEST_METHOD (Applesoft_HgrColorSweep_OneLinerRunsToCompletion)
    {
        HeadlessHost   host;
        EmulatorCore   core;
        size_t         consumed    = 0;
        HRESULT        hrReturn    = S_OK;
        uint64_t       startCycles = 0;
        uint64_t       elapsed     = 0;

        HRESULT   hr = host.BuildApple2e (core);



        AssertSucceeded (hr, L"BuildApple2e must succeed");
        Assert::IsTrue (core.HasApple2e(), L"//e wiring must be complete");

        core.PowerCycle();
        core.RunCycles  (kSweepColdBootCycles);

        consumed = KeystrokeInjector::InjectString (core, kSweepOneLiner);
        Assert::AreEqual (strlen (kSweepOneLiner), consumed,
            L"The whole one-liner must be consumed by the ROM input routine");

        hrReturn = KeystrokeInjector::InjectKey (
            core, KeystrokeInjector::kAppleReturn);
        AssertSucceeded (hrReturn, L"Return must be consumed");

        startCycles = core.cpu->GetTotalCycles();

        // Completion signal: the loop has reached its last mask AND that
        // mask's fill has written the final byte of the page. $FF at an
        // odd page byte is unique to mask $FF -- the only other mask that
        // could place it there is $80, whose pixel bits are $00 and so
        // never phase-flips.
        while (elapsed < kSweepCycleCeiling)
        {
            core.RunCycles (kSweepPollChunk);
            elapsed = core.cpu->GetTotalCycles() - startCycles;

            if (core.bus->ReadByte (kZpColorMask) == kLastColorMask &&
                core.bus->ReadByte (kHiresPage1LastByte) == kLastColorMask)
            {
                break;
            }
        }

        Assert::IsTrue (elapsed < kSweepCycleCeiling,
            L"The one-liner must finish all 256 steps within the ceiling");

        Assert::IsTrue (core.softSwitches->IsHiresMode(),
            L"The sweep must leave the //e in hi-res");
        Assert::IsTrue (core.softSwitches->IsMixedMode(),
            L"HGR leaves MIXED on, so the text window stays visible");

        VerifySweptPage (core, kLastColorMask);

        Logger::WriteMessage (std::format (
            "Applesoft one-liner: 256 steps in {} cycles "
            "({:.2f} s emulated at {:.4f} MHz, {:.2f} fills/sec).\n",
            elapsed,
            static_cast<double> (elapsed) / kCpuClockHz,
            kCpuClockHz / 1e6,
            static_cast<double> (kColorMaskCount) /
                (static_cast<double> (elapsed) / kCpuClockHz)).c_str());
    }
};

